#!/bin/bash

#SBATCH --job-name=ANTS
#SBATCH --ntasks-per-node=1
#SBATCH --mem=1G
#SBATCH --time=05:00:00

# module load ants
chmod +x brainwarp.sh
singularity exec docker://brainlife/ants:2.2.0-1bc ./brainwarp.sh
